// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ESTproto/BcPackage.proto

package com.botech.ywzx.netty.bean;

public final class BcPackageBuilder {
  private BcPackageBuilder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BcPackageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string bctype = 1;
    /**
     * <code>optional string bctype = 1;</code>
     *
     * <pre>
     *ҵ������
     * </pre>
     */
    boolean hasBctype();
    /**
     * <code>optional string bctype = 1;</code>
     *
     * <pre>
     *ҵ������
     * </pre>
     */
    java.lang.String getBctype();
    /**
     * <code>optional string bctype = 1;</code>
     *
     * <pre>
     *ҵ������
     * </pre>
     */
    com.google.protobuf.ByteString
        getBctypeBytes();

    // optional int32 bcpriority = 2;
    /**
     * <code>optional int32 bcpriority = 2;</code>
     *
     * <pre>
     *��Ϣ���ȼ�
     * </pre>
     */
    boolean hasBcpriority();
    /**
     * <code>optional int32 bcpriority = 2;</code>
     *
     * <pre>
     *��Ϣ���ȼ�
     * </pre>
     */
    int getBcpriority();

    // optional string clusteredid = 3;
    /**
     * <code>optional string clusteredid = 3;</code>
     *
     * <pre>
     *��ȺID
     * </pre>
     */
    boolean hasClusteredid();
    /**
     * <code>optional string clusteredid = 3;</code>
     *
     * <pre>
     *��ȺID
     * </pre>
     */
    java.lang.String getClusteredid();
    /**
     * <code>optional string clusteredid = 3;</code>
     *
     * <pre>
     *��ȺID
     * </pre>
     */
    com.google.protobuf.ByteString
        getClusteredidBytes();

    // optional string bcmessage = 4;
    /**
     * <code>optional string bcmessage = 4;</code>
     *
     * <pre>
     *ҵ����Ϣ
     * </pre>
     */
    boolean hasBcmessage();
    /**
     * <code>optional string bcmessage = 4;</code>
     *
     * <pre>
     *ҵ����Ϣ
     * </pre>
     */
    java.lang.String getBcmessage();
    /**
     * <code>optional string bcmessage = 4;</code>
     *
     * <pre>
     *ҵ����Ϣ
     * </pre>
     */
    com.google.protobuf.ByteString
        getBcmessageBytes();
  }
  /**
   * Protobuf type {@code BcPackage}
   */
  public static final class BcPackage extends
      com.google.protobuf.GeneratedMessage
      implements BcPackageOrBuilder {
    // Use BcPackage.newBuilder() to construct.
    private BcPackage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BcPackage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BcPackage defaultInstance;
    public static BcPackage getDefaultInstance() {
      return defaultInstance;
    }

    public BcPackage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BcPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              bctype_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              bcpriority_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              clusteredid_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              bcmessage_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.botech.ywzx.netty.bean.BcPackageBuilder.internal_static_BcPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.botech.ywzx.netty.bean.BcPackageBuilder.internal_static_BcPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage.class, com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage.Builder.class);
    }

    public static com.google.protobuf.Parser<BcPackage> PARSER =
        new com.google.protobuf.AbstractParser<BcPackage>() {
      public BcPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BcPackage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BcPackage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string bctype = 1;
    public static final int BCTYPE_FIELD_NUMBER = 1;
    private java.lang.Object bctype_;
    /**
     * <code>optional string bctype = 1;</code>
     *
     * <pre>
     *ҵ������
     * </pre>
     */
    public boolean hasBctype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string bctype = 1;</code>
     *
     * <pre>
     *ҵ������
     * </pre>
     */
    public java.lang.String getBctype() {
      java.lang.Object ref = bctype_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bctype_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bctype = 1;</code>
     *
     * <pre>
     *ҵ������
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBctypeBytes() {
      java.lang.Object ref = bctype_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bctype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 bcpriority = 2;
    public static final int BCPRIORITY_FIELD_NUMBER = 2;
    private int bcpriority_;
    /**
     * <code>optional int32 bcpriority = 2;</code>
     *
     * <pre>
     *��Ϣ���ȼ�
     * </pre>
     */
    public boolean hasBcpriority() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 bcpriority = 2;</code>
     *
     * <pre>
     *��Ϣ���ȼ�
     * </pre>
     */
    public int getBcpriority() {
      return bcpriority_;
    }

    // optional string clusteredid = 3;
    public static final int CLUSTEREDID_FIELD_NUMBER = 3;
    private java.lang.Object clusteredid_;
    /**
     * <code>optional string clusteredid = 3;</code>
     *
     * <pre>
     *��ȺID
     * </pre>
     */
    public boolean hasClusteredid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string clusteredid = 3;</code>
     *
     * <pre>
     *��ȺID
     * </pre>
     */
    public java.lang.String getClusteredid() {
      java.lang.Object ref = clusteredid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clusteredid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clusteredid = 3;</code>
     *
     * <pre>
     *��ȺID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClusteredidBytes() {
      java.lang.Object ref = clusteredid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clusteredid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string bcmessage = 4;
    public static final int BCMESSAGE_FIELD_NUMBER = 4;
    private java.lang.Object bcmessage_;
    /**
     * <code>optional string bcmessage = 4;</code>
     *
     * <pre>
     *ҵ����Ϣ
     * </pre>
     */
    public boolean hasBcmessage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string bcmessage = 4;</code>
     *
     * <pre>
     *ҵ����Ϣ
     * </pre>
     */
    public java.lang.String getBcmessage() {
      java.lang.Object ref = bcmessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bcmessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bcmessage = 4;</code>
     *
     * <pre>
     *ҵ����Ϣ
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBcmessageBytes() {
      java.lang.Object ref = bcmessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bcmessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      bctype_ = "";
      bcpriority_ = 0;
      clusteredid_ = "";
      bcmessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBctypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, bcpriority_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getClusteredidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getBcmessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBctypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, bcpriority_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getClusteredidBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getBcmessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BcPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.botech.ywzx.netty.bean.BcPackageBuilder.internal_static_BcPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.botech.ywzx.netty.bean.BcPackageBuilder.internal_static_BcPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage.class, com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage.Builder.class);
      }

      // Construct using com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bctype_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        bcpriority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        clusteredid_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        bcmessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.botech.ywzx.netty.bean.BcPackageBuilder.internal_static_BcPackage_descriptor;
      }

      public com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage getDefaultInstanceForType() {
        return com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage.getDefaultInstance();
      }

      public com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage build() {
        com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage buildPartial() {
        com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage result = new com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bctype_ = bctype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bcpriority_ = bcpriority_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.clusteredid_ = clusteredid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bcmessage_ = bcmessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage) {
          return mergeFrom((com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage other) {
        if (other == com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage.getDefaultInstance()) return this;
        if (other.hasBctype()) {
          bitField0_ |= 0x00000001;
          bctype_ = other.bctype_;
          onChanged();
        }
        if (other.hasBcpriority()) {
          setBcpriority(other.getBcpriority());
        }
        if (other.hasClusteredid()) {
          bitField0_ |= 0x00000004;
          clusteredid_ = other.clusteredid_;
          onChanged();
        }
        if (other.hasBcmessage()) {
          bitField0_ |= 0x00000008;
          bcmessage_ = other.bcmessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.botech.ywzx.netty.bean.BcPackageBuilder.BcPackage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string bctype = 1;
      private java.lang.Object bctype_ = "";
      /**
       * <code>optional string bctype = 1;</code>
       *
       * <pre>
       *ҵ������
       * </pre>
       */
      public boolean hasBctype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string bctype = 1;</code>
       *
       * <pre>
       *ҵ������
       * </pre>
       */
      public java.lang.String getBctype() {
        java.lang.Object ref = bctype_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bctype_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bctype = 1;</code>
       *
       * <pre>
       *ҵ������
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBctypeBytes() {
        java.lang.Object ref = bctype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bctype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bctype = 1;</code>
       *
       * <pre>
       *ҵ������
       * </pre>
       */
      public Builder setBctype(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bctype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bctype = 1;</code>
       *
       * <pre>
       *ҵ������
       * </pre>
       */
      public Builder clearBctype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bctype_ = getDefaultInstance().getBctype();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bctype = 1;</code>
       *
       * <pre>
       *ҵ������
       * </pre>
       */
      public Builder setBctypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bctype_ = value;
        onChanged();
        return this;
      }

      // optional int32 bcpriority = 2;
      private int bcpriority_ ;
      /**
       * <code>optional int32 bcpriority = 2;</code>
       *
       * <pre>
       *��Ϣ���ȼ�
       * </pre>
       */
      public boolean hasBcpriority() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 bcpriority = 2;</code>
       *
       * <pre>
       *��Ϣ���ȼ�
       * </pre>
       */
      public int getBcpriority() {
        return bcpriority_;
      }
      /**
       * <code>optional int32 bcpriority = 2;</code>
       *
       * <pre>
       *��Ϣ���ȼ�
       * </pre>
       */
      public Builder setBcpriority(int value) {
        bitField0_ |= 0x00000002;
        bcpriority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bcpriority = 2;</code>
       *
       * <pre>
       *��Ϣ���ȼ�
       * </pre>
       */
      public Builder clearBcpriority() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bcpriority_ = 0;
        onChanged();
        return this;
      }

      // optional string clusteredid = 3;
      private java.lang.Object clusteredid_ = "";
      /**
       * <code>optional string clusteredid = 3;</code>
       *
       * <pre>
       *��ȺID
       * </pre>
       */
      public boolean hasClusteredid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string clusteredid = 3;</code>
       *
       * <pre>
       *��ȺID
       * </pre>
       */
      public java.lang.String getClusteredid() {
        java.lang.Object ref = clusteredid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          clusteredid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clusteredid = 3;</code>
       *
       * <pre>
       *��ȺID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClusteredidBytes() {
        java.lang.Object ref = clusteredid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clusteredid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clusteredid = 3;</code>
       *
       * <pre>
       *��ȺID
       * </pre>
       */
      public Builder setClusteredid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clusteredid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clusteredid = 3;</code>
       *
       * <pre>
       *��ȺID
       * </pre>
       */
      public Builder clearClusteredid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        clusteredid_ = getDefaultInstance().getClusteredid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clusteredid = 3;</code>
       *
       * <pre>
       *��ȺID
       * </pre>
       */
      public Builder setClusteredidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        clusteredid_ = value;
        onChanged();
        return this;
      }

      // optional string bcmessage = 4;
      private java.lang.Object bcmessage_ = "";
      /**
       * <code>optional string bcmessage = 4;</code>
       *
       * <pre>
       *ҵ����Ϣ
       * </pre>
       */
      public boolean hasBcmessage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string bcmessage = 4;</code>
       *
       * <pre>
       *ҵ����Ϣ
       * </pre>
       */
      public java.lang.String getBcmessage() {
        java.lang.Object ref = bcmessage_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bcmessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bcmessage = 4;</code>
       *
       * <pre>
       *ҵ����Ϣ
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBcmessageBytes() {
        java.lang.Object ref = bcmessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bcmessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bcmessage = 4;</code>
       *
       * <pre>
       *ҵ����Ϣ
       * </pre>
       */
      public Builder setBcmessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bcmessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bcmessage = 4;</code>
       *
       * <pre>
       *ҵ����Ϣ
       * </pre>
       */
      public Builder clearBcmessage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bcmessage_ = getDefaultInstance().getBcmessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bcmessage = 4;</code>
       *
       * <pre>
       *ҵ����Ϣ
       * </pre>
       */
      public Builder setBcmessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        bcmessage_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BcPackage)
    }

    static {
      defaultInstance = new BcPackage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BcPackage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BcPackage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BcPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ESTproto/BcPackage.proto\"W\n\tBcPackage\022" +
      "\016\n\006bctype\030\001 \001(\t\022\022\n\nbcpriority\030\002 \001(\005\022\023\n\013c" +
      "lusteredid\030\003 \001(\t\022\021\n\tbcmessage\030\004 \001(\tB.\n\032c" +
      "om.botech.ywzx.netty.beanB\020BcPackageBuil" +
      "der"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BcPackage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BcPackage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BcPackage_descriptor,
              new java.lang.String[] { "Bctype", "Bcpriority", "Clusteredid", "Bcmessage", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
