
package com.botech.ywzx.netty.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImpl", targetNamespace = "http://webservice.netty.io.botech.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "process", targetNamespace = "http://webservice.netty.io.botech.com/", className = "com.botech.ywzx.netty.webservice.client.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://webservice.netty.io.botech.com/", className = "com.botech.ywzx.netty.webservice.client.ProcessResponse")
    @Action(input = "http://webservice.netty.io.botech.com/WebServiceImpl/processRequest", output = "http://webservice.netty.io.botech.com/WebServiceImpl/processResponse")
    public String process(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
